### PR TITLE
Ignores tmp directory

### PR DESCRIPTION
**Pull request by trycrmr**
If I'm reading the codebase correctly, these files are dynamically generated from the data sources when the app starts. The probably don't need to be committed with the codebase, no?

### CODE REVIEW

**Comment by trycrmr** [comment]
These files are causing nodemon to loop as well. In the meantime, ignoring the directory via nodemon's argument, `nodemon -i tmp`

**Comment by jensechu** [comment]
We need one of them that isn't actually tmp. I am going to move it out eventually.

**Comment by jensechu** [comment]
I'm closing because we can't actually merge this as it is, but when the time comes and we fix this I will ping you. 😄

**Comment by trycrmr** [comment]
Super duper thanks @jensechu !

**Pull request closed without merging**
